// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Fail loudly with a clear message instead of crashing inside createClient
  // with the opaque "supabaseUrl is required" error.
  // eslint-disable-next-line no-console
  console.error(
    "[supabase] Missing VITE_SUPABASE_URL and/or VITE_SUPABASE_PUBLISHABLE_KEY. " +
      "Add them to artifacts/insight-forge/.env and restart the dev server."
  );
}

// When the app is embedded inside the Replit preview iframe, direct
// localStorage access throws a SecurityError. This adapter tries localStorage
// first and silently falls back to an in-memory map so the app doesn't crash.
function makeSafeStorage() {
  try {
    localStorage.getItem("__probe__");
    return localStorage;
  } catch {
    const mem = new Map<string, string>();
    return {
      getItem: (key: string) => mem.get(key) ?? null,
      setItem: (key: string, value: string) => { mem.set(key, value); },
      removeItem: (key: string) => { mem.delete(key); },
    };
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL ?? "http://invalid.local", SUPABASE_PUBLISHABLE_KEY ?? "missing", {
  auth: {
    storage: makeSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});