import { Router, type IRouter } from "express";
import healthRouter from "./health";
import adminSystemRouter from "./admin-system";
import qualityGateRouter from "./quality-gate";
import recoveryRouter from "./recovery";
import aiRouter from "./ai/index.js";
import meRouter from "./me";
import projectsRouter from "./projects.js";
import brandsRouter from "./brands.js";
import eventsRouter from "./events.js";
import auditRouter from "./audit.js";
import adminRouter from "./admin.js";
import adminAssetsRouter from "./admin-assets.js";
import voiceLibraryRouter from "./voice-library.js";
import pageEventsRouter from "./page-events.js";
import authRouter from "./auth.js";
import seoRouter from "./seo/index.js";
import googleRouter from "./google/index.js";
import crossModuleRouter from "./cross-module.js";
import dashboardRouter from "./dashboard.js";
import { requireSeoRole } from "../middlewares/auth.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/admin/system", adminSystemRouter);
router.use("/admin", adminRouter);
router.use("/admin", adminAssetsRouter);
router.use("/quality-gate", qualityGateRouter);
router.use("/recovery", recoveryRouter);
router.use("/seo", requireSeoRole, seoRouter);
router.use("/google", googleRouter);
router.use("/cross-module", crossModuleRouter);
router.use("/ai", aiRouter);
router.use("/me", meRouter);
router.use("/dashboard", dashboardRouter);
router.use("/projects", projectsRouter);
router.use("/brands", brandsRouter);
router.use("/events", eventsRouter);
router.use("/audit", auditRouter);
router.use("/voice-library", voiceLibraryRouter);
router.use("/page-events", pageEventsRouter);

export default router;
